//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tinytots.English.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accent()
        {
            this.ProseActivities = new HashSet<ProseActivity>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ImageId { get; set; }
        public string British { get; set; }
        public string American { get; set; }
    
        public virtual Image Image { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProseActivity> ProseActivities { get; set; }
    }
}
