//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tinytots.English.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonPageMapping
    {
        public int Id { get; set; }
        public Nullable<int> LessonId { get; set; }
        public Nullable<int> PageId { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        public virtual Page Page { get; set; }
    }
}
