//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tinytots.English.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vocabulary
    {
        public int Id { get; set; }
        public Nullable<int> ImageId { get; set; }
        public string Word { get; set; }
        public string Synonym { get; set; }
    
        public virtual Image Image { get; set; }
    }
}
